
name: "Test_input"
description: "Test_input"
version: "1.1.5"
slug: "Test_input"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - "/dev/video0:/dev/video0:rwm"
startup: services
ports:
  8000/tcp: 8000

options:
  head:
    description: "Angle of the head section (0-100)"
    type: int
    required: true
    example: 50
schema:
  head:
    type: int
    minimum: 0
    maximum: 100
