name: LED Control
description: "Control an LED"
version: "1.0.0"
slug: led_control
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"
  startup: services
ports:
  8000/tcp: 8000