name: "RS485"
version: "1.0.1"
slug: "gpio_addon"
description: "An example Add-on to control GPIO."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: application
boot: manual

devices:
  - "/dev/ttyAMA0:/dev/ttyAMA0:rwm"
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"

options: {}
schema: {}
