name: "RS485"
version: "1.1.27"
slug: "gpio_addon"
description: "Control bed through RS485 protocol "
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: application
boot: manual

devices:
  - "/dev/ttyAMA0:/dev/ttyAMA0:rwm"
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"

options:
  start_state:
    description: ""
    type: bool
    required: true
    example: false
  first_state: 
    description: ""
    type: bool
    required: true
    example: false
  pause_state:
    description: ""
    type: bool
    required: true
    example: false
  head: 
    description: ""
    type: int
    required: true
    example: 50
  foot:
    description: ""
    type: int
    required: true
    example: 50
  lean: 
    description: ""
    type: int
    required: true
    example: 50
schema: 
  start_state: bool 
  first_state: bool 
  pause_state: bool 
  head: int 
  foot: int 
  lean: int 
