name: "RS485"
version: "1.0.8"
slug: "gpio_addon"
description: "Control bed through RS485 protocol "
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: application
boot: manual

devices:
  - "/dev/ttyAMA0:/dev/ttyAMA0:rwm"
  - "/dev/gpiochip0:/dev/gpiochip0:rwm"

options:
  start_state:
    description: ""
    type: int
    required: true
    example:
  first_state: 
    description: ""
    type: int
    required: true
    example: 
  pause_state:
    description: ""
    type: int
    required: true
    example:
  head: 
    description: ""
    type: int
    required: true
    example: 
  foot:
    description: ""
    type: int
    required: true
    example:
  lean: 
    description: ""
    type: int
    required: true
    example: 
schema: 
  start_state:
  first_state:
  pause_state:
  head:
  foot:
  lean:
