
name: "Hello_world"
description: "Hello_world"
version: "1.0.0"
slug: "Hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000

options:
  head:
    description: "Angle of the head section (0-100)"
    type: int
    required: true
    example: 50
schema:
  head:
    type: int
    minimum: 0
    maximum: 100
