name: "Hello World"
version: "1.0.0"
slug: "hello_world"
description: "A simple Hello World add-on for Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options: {}
schema: {}