
name: "Pose Detection Camera"
description: "Pose detection camera stream using MediaPipe and OpenCV."
version: "1.0.5"
slug: "pose_camera"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: services
ports:
  8000/tcp: 8000
