name: "Camera Stream Add-on"
version: "1.0.0"
slug: "camera_stream"
description: "Add-on to stream camera feed to Home Assistant"
arch:
  - aarch64
  - armv7
  - amd64
  - i386
startup: application
boot: auto
ports:
  8080/tcp: 8080
options:
  camera_device: "/dev/video0"
schema:
  camera_device: str

